#pragma once
#include <wx/defs.h>

enum {
    ID_LoginButton = wxID_HIGHEST + 1, 
    ID_SignupButton,
    ID_SignupSubmitButton,
    ID_LogoutButton,
    ID_LoginSignupButton,
    ID_ViewProducts,
    ID_ViewStore,
    ID_ViewCustomers,
    ID_LogoutButtonAdmin,
    ID_AddBook,
    ID_SaveProductButton,
    ID_CANCEL,
    ID_SubmitStore,
    ID_AddStationery,
    ID_AddBookInStore,
    ID_RefreshBtnStoreView,
    ID_EditBtnStoreView,
    ID_AddProductBtnStoreView,
    ID_AddStatBtnStoreView,
    ID_CancelBtnAddStat,
    ID_ClearBtnAddStat,
    ID_SaveBtnAddStat,
    ID_AddStatAdmin,
    ID_AddStore,
    ID_RefreshBtnStoreManagers,
    ID_ViewStoreRC,
    ID_RightClickDashboardAdmin,
    ID_BackViewStore,
    ID_RightClickViewStore,
    ID_ViewStoreVC,
    ID_BackBtnVS,
    ID_BackBtnVB,
    ID_ViewProductCart, 
    ID_RemoveProductCart,
    ID_BackCart,
    ID_DeleteCart,
    ID_RefreshCart,
    ID_ProceedCart,
    ID_BackButtonOP,
    ID_RefreshListOP,
    ID_CancelOrderOP,
    ID_PlaceOrderOP,
    ID_BackDisplayOrder,
    ID_OrderDU, ID_LogoutDU,
    ID_RefreshDisplayOrder,
    ID_ViewOrder,
    ID_ViewCartDU,
    ID_RightClickViewOrder,
    ID_deleteOrder,
};